name: CI Calculadora

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    name: Validar HTML/JS
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Validar HTML
      uses: actions/github-script@v6
      with:
        script: |
          // Simple validación de que existe index.html
          const fs = require('fs');
          if (!fs.existsSync('index.html')) {
            core.setFailed('No se encontró archivo index.html');
          }
    
    - name: Verificar JS
      run: |
        if [ ! -f "script.js" ]; then
          echo "::error::No se encontró script.js"
          exit 1
        fi
        
  deploy:
    needs: validate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Desplegar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
